#!/bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &
pkill -USR1 -x sxhkd

i=1
for monitor in $(bspc query -M); do
	bspc monitor $monitor \
		--reset-desktops $i/{1..9}
	let i++
done

bspc config border_width 1
bspc config window_gap   0
bspc config normal_border_color  '#000000'
bspc config focused_border_color '#FFFFFF'

bspc config focus_follows_pointer true
bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config pointer_modifier      mod3

bspc rule -a *:dropdown state=floating sticky=on
bspc rule -a mpv        state=floating
bspc rule -a vlc        state=floating
bspc rule -a feh        state=floating
bspc rule -a Emacs      state=tiled

"$(dirname $0)"/autorun.sh
